"""autogenerate current databse schema

Revision ID: 89ca5ba46cb4
Revises: a835bfb72cfc
Create Date: 2024-04-19 18:46:38.179457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89ca5ba46cb4'
down_revision: Union[str, None] = 'a835bfb72cfc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
